# Generated by Django 3.1.6 on 2021-03-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='cell',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='dateofbirth',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='district',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='firstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='gender',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='harvesttype',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='pincode',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='sector',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='village',
            field=models.CharField(default='', max_length=255),
        ),
    ]
