# Generated by Django 3.1.6 on 2021-03-17 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('leaderphone', models.CharField(max_length=255)),
                ('harvesttype', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EndpointAfripay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('transaction_ref', models.CharField(max_length=234)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=234)),
                ('payment_method', models.CharField(max_length=234)),
                ('client_token', models.CharField(max_length=234)),
            ],
        ),
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('harvesttype', models.CharField(max_length=255)),
                ('dateofbirth', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('Cooperative', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('cell', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pay_date', models.DateField(auto_now=True)),
                ('pay_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regfarmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('dateofbirth', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('regCooperative', models.CharField(max_length=255)),
                ('farmercode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=20)),
                ('Cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cooperative')),
            ],
        ),
        migrations.CreateModel(
            name='Recorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('cooperativename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cooperative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profilecooperative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=' cooperative Logo')),
                ('cooperativename', models.CharField(max_length=255)),
                ('activate_on', models.DateField(auto_now=True)),
                ('farmers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payharvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_amount', models.CharField(max_length=255)),
                ('farmercode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.regfarmer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.CharField(max_length=255)),
                ('farmercode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.regfarmer')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurancetype', models.CharField(choices=[('imyaka15', 'imyaka15'), ('imyaka10', 'imyaka10'), ('imyaka itanu', 'imyaka itanu'), ('umwaka umwe', 'umwaka umwe')], max_length=255)),
                ('farmercode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.regfarmer')),
            ],
        ),
        migrations.CreateModel(
            name='Harvestrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('donedate', models.DateField(auto_now=True)),
                ('donetime', models.TimeField(auto_now=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.farmers')),
            ],
        ),
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.FloatField(default=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
