# Generated by Django 3.1.6 on 2021-03-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210320_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperative',
            name='district',
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='harvesttype',
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='leaderphone',
        ),
    ]
